### ISSUE TITLE
I made this Heroku Comptible

### ISSUE THREAD

**Issue by jeet-private** [lioialessandro/LyricsGramBot#2]
**I made this Heroku comptible ,kindly check that if it works or not  👍** <br>

*https://github.com/jeet-private/LyricsGramBot*

<br>

**This is my Original ID:** <br>
*https://github.com/cachecleanerjeet*

**Comment by lioialessandro** [comment]
Hi,
It's already Heroku compatible. It deploys to Heroku every time there is a commit to master.
